{% set name = "bitarray" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b03c49d1a2eb753cc6090053f1c675ada71e1c3ea02011f1996cf4c2b6e9d6d6

build:
  number: 0
  # https://github.com/ilanschnell/bitarray/issues/99
  skip: true  # [python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - bitarray

about:
  home: https://github.com/ilanschnell/bitarray
  license: PSF-2.0
  license_file: LICENSE
  summary: efficient arrays of booleans -- C extension
  description: |
    Bitarray provides an object type which efficiently represents an array of
    booleans. Bitarrays are sequence types that behave very similarly
    to usual lists. All functionality is implemented in C.
  doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
  doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
  dev_url: https://github.com/ilanschnell/bitarray

extra:
  recipe-maintainers:
    - nehaljwani
