{% set name = "bitarray" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2083dc20f0d828a7cdf7a16b20dae56aab0f43dc4f347a3b3039f6577992b03

build:
  number: 0
  # https://github.com/ilanschnell/bitarray/issues/99
  skip: true  # [python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - bitarray

about:
  home: https://github.com/ilanschnell/bitarray
  license: PSF-2.0
  license_file: LICENSE
  summary: efficient arrays of booleans -- C extension
  description: |
    Bitarray provides an object type which efficiently represents an array of
    booleans. Bitarrays are sequence types that behave very similarly
    to usual lists. All functionality is implemented in C.
  doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
  doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
  dev_url: https://github.com/ilanschnell/bitarray

extra:
  recipe-maintainers:
    - nehaljwani
