{% set name = "bitarray" %}
{% set version = "3.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/bb/9b/ca307b554eaa233d004cae07d5594f9d45affd1f8e118687059aa06fcc6b/bitarray-{{ version }}.tar.gz
  sha256: 2675a0c17c0b2d12d0fbcf3b27eb833f96936a588da47ac445c0743c5aa69e6b

build:
  number: 0
  # https://github.com/ilanschnell/bitarray/issues/99
  skip: true  # [python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - bitarray

about:
  home: https://github.com/ilanschnell/bitarray
  license: PSF-2.0
  license_file: LICENSE
  summary: efficient arrays of booleans -- C extension
  description: |
    Bitarray provides an object type which efficiently represents an array of
    booleans. Bitarrays are sequence types that behave very similarly
    to usual lists. All functionality is implemented in C.
  doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
  doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
  dev_url: https://github.com/ilanschnell/bitarray

extra:
  recipe-maintainers:
    - nehaljwani
