schema_version: 1

context:
  version: "3.8.0"

package:
  name: bitarray
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/bitarray/bitarray-${{ version }}.tar.gz
  sha256: 3eae38daffd77c9621ae80c16932eea3fb3a4af141fb7cc724d4ad93eff9210d

build:
  number: 2
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - setuptools >=42.0.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - bitarray
      pip_check: true
  - script:
    - python -m bitarray.test_bitarray -v
    requirements:
      run:
        - python

about:
  license: PSF-2.0
  license_file: LICENSE
  summary: efficient arrays of booleans -- C extension
  description: |
    Bitarray provides an object type which efficiently represents an array of
    booleans. Bitarrays are sequence types that behave very similarly
    to usual lists. All functionality is implemented in C.
  homepage: https://github.com/ilanschnell/bitarray
  repository: https://github.com/ilanschnell/bitarray
  documentation: https://pypi.python.org/pypi/bitarray/

extra:
  recipe-maintainers:
    - nehaljwani
    - mgorny
